<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }

        .logo {
            width: 200px;
            float: right;
        }

        .info {
            text-align: left;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
        }

        .table th,
        .table td {
            border: 1px solid black;
            padding: 5px;
        }

        .footer {
            position: absolute;
            bottom: 20px;
            left: 0;
            right: 0;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="logo">
            <img src="{{ public_path('/assets/images/UJiMakrologoo.png') }}" width="100" class="logo" alt="Logo">
        </div>
        <div class="info">
            <div style="text-align: left;">
                <h2>Report Title</h2>
                <p>Report generated on: {{ date('Y-m-d H:i:s') }}</p>
                <p>Additional Information:</p>
                <ul>
                    <li>Generated by: {{auth()->user()->user_name}}</li>
                    <li>Role: {{auth()->user()->user_role}}</li>
                    <li>Email: {{auth()->user()->user_email}}</li>
                </ul>
            </div>
        </div>


    </div>
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Location</th>
                <th>Date</th>
                <th>Average Score</th>
                <th>Total Macro</th>
            </tr>
        </thead>
        <tbody>
            @foreach($records as $r)
            @php
            $makro = explode('|', $r->selected_makro);
            $makros = [];
            $totalmakro = 0;
            foreach ($makro as $data) {
            $makro = json_decode($data, true);
            $makros[] = $makro;
            $totalMakro = count(array_unique(array_column($makros, 'makro_id')));
            }
            @endphp
            <tr>
                <td>{{$loop->iteration}}</td>
                <td>{{$r->user->user_name}}</td>
                <td>{{$r->user->user_email}}</td>
                <td>{{$r->location}}</td>
                <td>{{$r->created_at}}</td>
                <td>{{$r->record_average}}</td>
                <td>{{$totalMakro}}</td>
            </tr>


            @endforeach
            <!-- Add more rows as needed -->
        </tbody>
    </table>
    <div class="footer">
        <!-- Add footer content if desired -->
    </div>
</body>

</html>