<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }

        .logo {
            width: 200px;
            float: right;
        }

        .info {
            text-align: left;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
        }

        .table th,
        .table td {
            border: 1px solid black;
            padding: 5px;
        }

        .footer {
            position: absolute;
            bottom: 20px;
            left: 0;
            right: 0;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="logo">
            <img src="{{ public_path('/assets/images/UJiMakrologoo.png') }}" width="100" class="logo" alt="Logo">
        </div>
        <div class="info">
            <div style="text-align: left;">

                @php
                $water_status = "";

                if ($records->record_average >= 7.6 && $records->record_average <= 10) { $water_status="Very Clean" ; } else if ($records->record_average >= 5.1 && $records->record_average <= 7.59) { $water_status="Almost Clean" ; } else if ($records->record_average >= 2.6 && $records->record_average <= 5.09) { $water_status="Almost Dirty" ; } else if ($records->record_average >= 1.0 && $records->record_average <= 2.59) { $water_status="Dirty" ; } else if ($records->record_average >= 0 && $records->record_average <= 0.9) { $water_status="Very Dirty" ; } else { $water_status="Invalid Score" ; } @endphp <h2>Individual Report</h2>
                                    <p>Report generated on: {{ date('Y-m-d H:i:s') }}</p>
                                    <p>Generated by: {{auth()->user()->user_name}}</p>
                                    <p>Role: {{auth()->user()->user_role}}</p>
                                    <p>Email: {{auth()->user()->user_email}}</p>
                                    <p>Additional Information:</p>
                                    <ul>
                                        <li>User Info: {{$records->user->user_name}}</li>
                                        <li>Role: {{$records->user->user_role}}</li>
                                        <li>Email: {{$records->user->user_email}}</li>
                                        <li>Water Status: {{$water_status}}</li>
                                        <li>Location: {{$records->location}}</li>
                                        <li>Date: {{$records->user->created_at}}</li>
                                    </ul>
            </div>
        </div>


    </div>
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Macro Name</th>
                <th>Macro Mark</th>
                <th>Macro Image</th>
            </tr>
        </thead>
        <tbody>
            @foreach($makros as $r)
            <tr>
                <td>{{$loop->iteration}}</td>
                <td>{{$r['makro_name']}}</td>
                <td>{{$r['makro_mark']}}</td>
                <td style="height: 50; ">
                    <img src="{{ public_path('/assets/images/makro/' .$r['makro_image']) }}" width="50" height="50" class="logo" alt="Logo">
                </td>
            </tr>


            @endforeach
            <!-- Add more rows as needed -->
        </tbody>
    </table>
    <div class="footer">
        <!-- Add footer content if desired -->
    </div>
</body>

</html>